### ISSUE TITLE
(enhancement) Implement a proper health check probe

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/wg-access-server#100]
We may want to add some kind of health check to our wg-access-server implementation. To achieve this, we may need to add a health check endpoint (see: https://docs.mattermost.com/manage/health-checks.html). This is especially useful on k8s clusters, as the failing pods can be automatically terminated and replaced by a newly scheduled one (https://kubernetes.io/docs/concepts/workloads/pods/pod-lifecycle/).

**Comment by DasSkelett** [comment]
There already exists a basic one: 
https://github.com/freifunkMUC/wg-access-server/blob/master/internal/services/health.go
https://github.com/freifunkMUC/wg-access-server/blob/349f5faee72371ad82e5055726ce389974b35880/cmd/serve/main.go#L167-L168

Seems to lack documentation.

It doesn't do any real checks though, like checking if the Wireguard interface is still up and the database can be queried or so.
