### ISSUE TITLE
Add /lib/modules volume to docker compose docs

### ISSUE THREAD

**Issue by adamhl8** [freifunkMUC/wg-access-server#103]
In the Docker Compose part of the docs and in the docker-compose.yml file itself within the repo, it's not mentioned that the `/lib/modules` volume needs to be mounted for the container to start. The docker run command provided at the top of the readme has this, so I think it should be added to the docker compose examples as well.

**Comment by adamhl8** [comment]
Ah, you're right, sorry. Turns out my container was crashing because I had IPv6 enabled. I disabled IPv6 and added that volume at the same time and assumed the volume was the issue.

**Comment by GoliathLabs** [comment]
But you're right, we need /lib/modules for ip6tables inside the container for ipv6 support
