### ISSUE TITLE
Add option to configure nodePort

### ISSUE THREAD

**Issue by elcomtik** [freifunkMUC/wg-access-server#127]
I'm deploying wg-access-server by helm chart to my self hosted k8s. I would like to use service type nodePort and point dnat firrewall rule on it. 

Because of this I need to configure static nodePort. This is currently not possible as I looked into [service template](https://github.com/freifunkMUC/wg-access-server/blob/master/deploy/helm/wg-access-server/templates/service.yaml).

**Comment by DasSkelett** [comment]
https://github.com/freifunkMUC/wg-access-server/pull/125 adds the ability to configure `port` and `targetPort`, but that's probably not enough for you, right? You also need the ability to configure the `nodePort` option?

**Comment by elcomtik** [comment]
yes, nodePort is additional setting

**Comment by elcomtik** [comment]
Now, when #125 is merged I can make PR for this enhancement. It will be pretty simple. 

@DasSkelett are you interested in this contribution?

**Comment by DasSkelett** [comment]
Yes, please go ahead! We are very thankful for contributions, especially regarding Helm.

**Comment by elcomtik** [comment]
@DasSkelett PR ready, can you approve it for tests?

**Comment by DasSkelett** [comment]
Fixed by #129
