### ISSUE TITLE
how to use grpc calls

### ISSUE THREAD

**Issue by warlock9600** [freifunkMUC/wg-access-server#150]
hi everyone!
i'm run wg-access-server in kubernetes with postgres backend, but not understand how to use grpc calls to automate user CRUD operations

can you tell me how to implement access to grpc?

**Comment by DasSkelett** [comment]
I'm not sure if I understand the question correctly, do you want to create users through the gRPC API?
If so, that's not possible. The wg-access-server only supports either specifying basic auth users statically in the config file, or through an OIDC backend, or a GitLab instance (which is also implemented through OIDC). See https://www.freie-netze.org/wg-access-server/4-auth/

If you want to have dynamic user management, you need to set up some Identity and Access Management like [Keycloak](https://www.keycloak.org/) and connect it through OIDC.

**Comment by warlock9600** [comment]
ok, i'm wrong %)


i meant creating/deleting peers using gRPC API
`devices.proto` provides several methods (AddDeviceReq, ListDevicesReq, etc) - how to use them from another application?

**Comment by DasSkelett** [comment]
You should be able to generate the code from the .proto files for the language you want, then hook it together. You can check the frontend code as an example, e.g.
https://github.com/freifunkMUC/wg-access-server/blob/ad98910320ff1bda5922b384d0bd3893e906e28b/website/src/components/AddDevice.tsx#L41-L67
for creating a wireguard-native ini-style config file after adding a new device.

**Comment by warlock9600** [comment]
uh, nope

for example

i have locally installed Postman with added proto scheme from repository
how to make from Postman gRPC request to proto.Devices with ListAllDevices method?

**Comment by DasSkelett** [comment]
I don't know Postman aside from that it exists, but this could be a start https://blog.postman.com/postman-now-supports-grpc/ ?
But we use gRPC-Web to be precise, which might or might not work with Postman.

But I think I need to point out that the API isn't meant as a standalone one, it's primary purpose is the consumption through the wg-access-server frontend. I also can't promise that we don't break it every now and then.

Why do you want to call it through Postman? Just as a gateway / load balancer? If so, a normal HTTP reverse proxy should work just fine, in the end, thanks to gRPC-Web, it's just HTTP/1.1 or HTTP/2 requests.

**Comment by warlock9600** [comment]
hmm, can you give an example of how to use any of these api requests via http?

**Comment by DasSkelett** [comment]
Not really, no. Because while the underlying transport is HTTP, the POST body data is protobuf-encoded (and maybe some grpc-specific additions?). You should let protoc's code generation generate the client code for whatever programming language you need and build anything else around that. See https://developers.google.com/protocol-buffers/ and https://grpc.io/ for basics about protocol buffers and gRPC.

But as I said, I really don't see the need to do this. We have a working web UI, if there are issues with it please open bug reports or feature requests. Unless you explain what you actually want to do and what your ultimate goal is I won't be able to help you.

**Comment by DasSkelett** [comment]
Closing now, please come back with more details if you need more help.
