### ISSUE TITLE
pgwatcher doesn't receive notifications behind pgbouncer

### ISSUE THREAD

**Issue by warlock9600** [freifunkMUC/wg-access-server#151]
hi everyone!
i'm run wg-access-server in kubernetes with postgres backend with several replicas of app.

But when I create new peers through the interface, they do not appear in the config until the pods are restarted.

how to fix this issue?

log example:
```
time="2022-04-02T14:37:34Z" level=debug msg="SELECT * FROM \"devices\"  " file="sql.go:32" module=gorm rows=4 src_ref="/code/internal/storage/sql.go:158" type=sql values="[]"
time="2022-04-02T14:37:34Z" level=debug msg="found 4 device(s)" file="sql.go:161"
time="2022-04-02T14:37:34Z" level=debug msg="saving device admin/qwer" file="sql.go:144"
time="2022-04-02T14:37:34Z" level=debug msg="UPDATE \"devices\" SET \"owner_name\" = $1, \"owner_email\" = $2, \"owner_provider\" = $3, \"public_key\" = $4, \"address\" = $5, \"created_at\" = $6, \"last_handshake_time\" = $7, \"receive_bytes\" = $8, \"transmit_bytes\" = $9, \"endpoint\" = $10  WHERE \"devices\".\"owner\" = $11 AND \"devices\".\"name\" = $12" file="sql.go:32" module=gorm rows=0 src_ref="/code/internal/storage/sql.go:145" type=sql values="[admin  basic QM+rwmZstn4tRUUX0OWluHwRzz28PoaTZ0BtHfr+JB8= 10.44.0.6/32 2022-04-02 14:37:34.786852114 +0000 UTC m=+70.430682253 <nil> 0 0  admin qwer]"
time="2022-04-02T14:37:34Z" level=debug msg="SELECT * FROM \"devices\"  WHERE \"devices\".\"owner\" = $1 AND \"devices\".\"name\" = $2 ORDER BY \"devices\".\"owner\" ASC LIMIT 1" file="sql.go:32" module=gorm rows=0 src_ref="/code/internal/storage/sql.go:145" type=sql values="[admin qwer]"
time="2022-04-02T14:37:34Z" level=debug msg="INSERT INTO \"devices\" (\"owner\",\"owner_name\",\"owner_email\",\"owner_provider\",\"name\",\"public_key\",\"address\",\"created_at\",\"last_handshake_time\",\"receive_bytes\",\"transmit_bytes\",\"endpoint\") VALUES ($1,$2,$3,$4,$5,$6,$7,$8,$9,$10,$11,$12) RETURNING \"devices\".\"owner\"" file="sql.go:32" module=gorm rows=1 src_ref="/code/internal/storage/sql.go:145" type=sql values="[admin admin  basic qwer QM+rwmZstn4tRUUX0OWluHwRzz28PoaTZ0BtHfr+JB8= 10.44.0.6/32 2022-04-02 14:37:34.786852114 +0000 UTC m=+70.430682253 <nil> 0 0 ]"
time="2022-04-02T14:37:34Z" level=info msg="finished unary call with code OK" file="options.go:220" grpc.code=OK grpc.method=AddDevice grpc.service=proto.Devices grpc.start_time="2022-04-02T14:37:34Z" grpc.time_ms=18.03 span.kind=server system=grpc trace.id=f1e0c00f-6832-4031-bd1c-c8285c084e8d
time="2022-04-02T14:37:34Z" level=debug msg="SELECT * FROM \"devices\"  WHERE (owner = $1)" file="sql.go:32" module=gorm rows=5 src_ref="/code/internal/storage/sql.go:156" type=sql values="[admin]"
time="2022-04-02T14:37:34Z" level=debug msg="found 5 device(s)" file="sql.go:161"
time="2022-04-02T14:37:34Z" level=info msg="finished unary call with code OK" file="options.go:220" grpc.code=OK grpc.method=ListDevices grpc.service=proto.Devices grpc.start_time="2022-04-02T14:37:34Z" grpc.time_ms=3.435 span.kind=server system=grpc trace.id=70b96087-2b12-4cda-8e58-51fa8352a350
```

**Comment by DasSkelett** [comment]
Do they only not appear for the replicas, or also not even in the instance you created it in?
Are you only running replicas of wg-access-server, or also PostgreSQL in HA?

I think the HA functionality of wg-access-server was still experimental when we forked the project, and I never tried it out myself. So it's very possible it doesn't quite work yet, but hopefully we can fix it.

**Comment by warlock9600** [comment]
yes, when i scale replicas to one, this issue remains.

for example - now i'm scale replicas to one piece, and from web interface delete all peers.
after - attach shell directly to pod, and input `wg` command - in output all peers are visible.

meanwhile, in log i see that message:
`time="2022-04-02T15:15:12Z" level=debug msg="found 0 device(s)" file="sql.go:161"` 

and after pod restart, all peers deleted.

Postgres - in HA mode via pgbouncer, and when I created peers in the interface - they instantly appeared in the database

**Comment by DasSkelett** [comment]
Hm, I can't reproduce this yet, running it "bare-metal". I just started it with a PostgreSQL as storage backend, and the new peer shows up instantly in the output of `wg` after creating it in the UI.

There are a few lines missing from your log that I'd expect to show up, which indicate that the postgres-listener doesn't even receive notifications about the changes:
```
DEBU[0071]pgevents.go:82 received data from channel: pgevents_event 
DEBU[0071]devices.go:32 storage event: device added: admin/psql1     
```

Can you check if there's a line containing `creating postgres watcher` further up in the log, shortly after starting the pod(s)? And maybe any error message around it?

**Comment by warlock9600** [comment]
`time="2022-04-02T15:49:01Z" level=debug msg="creating postgres watcher" file="pgwatcher.go:16"`

¯\_(ツ)_/¯

**Comment by warlock9600** [comment]
arrrrrrrghgrhr, try that w/o pgbouncer - ok

**Comment by DasSkelett** [comment]
Aha! That is interesting. So pg-events doesn't like going through pgbouncer.
I'm wondering if pgbouncer doesn't relay the notifications that pg-events relies on.
I'll see if I can reproduce it now, but if you are also able to narrow it down please let me know.

For now I guess the recommendation is to connect to PostgreSQL directly, without pgbouncer in front.

**Comment by DasSkelett** [comment]
This sounds like the culprit:
https://www.pgbouncer.org/features.html
> **SQL feature map for pooling modes**
>
> Feature | Session pooling | Transaction pooling
> -- | -- | --
> LISTEN/NOTIFY | Yes | Never

Can you confirm whether your pgbouncer is running in "Transaction pooling" mode, and if so whether setting it to "Session Pooling" fixes it?

**Comment by DasSkelett** [comment]
I wonder if there's a way to detect that, because then we could fallback to the gormwatcher. HA would be broken both ways (needs to be documented), but it would allow single-instance deployments behind a "Transaction Pooling" pgbouncer.

**Comment by warlock9600** [comment]
yeah, at "session" mode of pgbouncer it works fine!

thank you!
