### ISSUE TITLE
[feature] Customize config filename

### ISSUE THREAD

**Issue by nathanael-h** [freifunkMUC/wg-access-server#168]
This is a feature request. 
I'd like to be able to customize the config filename. Because this filename is used as connection name in clients (or at least on different Linux using network manager). 
I saw it is harcoded here https://github.com/freifunkMUC/wg-access-server/blob/b71ad3fbfedce8c92c4fda0afdc2d3ee327e8dc0/website/src/components/GetConnected.tsx#L35 
Maybe I could try a PR, with some tips.

**Comment by DasSkelett** [comment]
Just so I understand the details, does renaming the file after downloading not work, or would it just be for convenience to avoid this step?

Do you have in mind editing the filename in the web UI right before downloading (so users can choose it themselves), or setting it globally in the server config.yaml for everyone?

**Comment by nathanael-h** [comment]
Yes, I can rename the file after downloading, but for convenience I would like to avoid this. 

I was thinking of defining the name in an optional setting, that would be applied server-wide.

**Comment by DasSkelett** [comment]
I see. In this case it needs a new config option here:
https://github.com/freifunkMUC/wg-access-server/blob/master/internal/config/config.go

Maybe also a commandline flag here:
https://github.com/freifunkMUC/wg-access-server/blob/b71ad3fbfedce8c92c4fda0afdc2d3ee327e8dc0/cmd/serve/main.go#L38-L63

To communicate it to the frontend it should probably sent as part of the `InfoRes` response to the `Info` gRPC call, which contains some global, device independent data that the frontend needs:
https://github.com/freifunkMUC/wg-access-server/blob/master/proto/server.proto

...which the backend populates here:
https://github.com/freifunkMUC/wg-access-server/blob/b71ad3fbfedce8c92c4fda0afdc2d3ee327e8dc0/internal/services/server_service.go#L59-L70

then you should be able to read it from `AppState.Info` in the fronted.

**Comment by nathanael-h** [comment]
Hello @DasSkelett would it be possible to build and release a new image with this feature?
