### ISSUE TITLE
how create preset user?

### ISSUE THREAD

**Issue by pprometey** [freifunkMUC/wg-access-server#180]
I want wg-access-server to be used in conjunction with Wirehole, user friendly. How to create a preset user?

**Comment by DasSkelett** [comment]
What do you consider a preset user?

**Comment by pprometey** [comment]
so that I can connect via VPN to the Wireguard server, without creating a user via the UI.
config file

**Comment by pprometey** [comment]
i like going https://github.com/linuxserver/docker-wireguard#parameters when i can set the variable -e PEERS=1

**Comment by pprometey** [comment]
first i used this project but it is very buggy and unpredictable https://github.com/linuxserver/docker-wireguard
I deploy it on oracle cloud arm64 base

**Comment by DasSkelett** [comment]
Basic Auth users with access to the web UI for generating their own device configs can be hardcoded in the config file under the `auth.basic:`, see https://www.freie-netze.org/wg-access-server/4-auth/
Alternatively you can hook up your own OIDC backend.

But this is different from how the linuxserver/wireguard image works, which generates actual WireGuard config files right away and outputs them in the log.
wg-access-server has a web UI, and every user has their own account for it and can add clients/devices to generate WireGuard configs.

**Comment by pprometey** [comment]
I just didn't want to release the Wireguard control panel into the public space, but wanted to hide it behind a VPN

**Comment by pprometey** [comment]
Thanks Freifunkm , you helped me a lot. A little later I will show the results of your help.
