### ISSUE TITLE
5xx after failed auth

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/wg-access-server#201]
If you fail to auth to the service because of wrong password or wrong identity provider, the page will always return a 5xx error.

Instead of this there should be a redirect to the login page to try again.

**Comment by DasSkelett** [comment]
Hm, this might actually be the same problem as https://github.com/freifunkMUC/wg-access-server/issues/179#issuecomment-1156789316, especially if you encountered it after aborting the login flow from KeyCloak.
