### ISSUE TITLE
`go118/netip` dependency not available anymore

### ISSUE THREAD

**Issue by marob** [freifunkMUC/wg-access-server#204]
It looks like `golang.zx2c4.com/go118/netip` dependency doesn't exist anymore, making dependency retrieval fail.

I've found a workaround by replacing the dependency by [`github.com/thepudds/go118-netip`](https://github.com/thepudds/go118-netip) by adding the following configuration in the `go.mod` file:
```
replace golang.zx2c4.com/go118/netip v0.0.0-20211111135330-a4a02eeacf9d => github.com/thepudds/go118-netip 2817a0d675019be134f580008d855ab0f9650ee2
```

But as [their README](https://github.com/thepudds/go118-netip/blob/master/README.md) says, it "should not be relied upon", so it's only a quick workaround.

I suppose a better solution would be to migrate to go 1.18 which, if I understand well, would not require this dependency anymore, but I'm letting you find the best solution to fix this issue.

**Comment by DasSkelett** [comment]
What error do you get? It still downloads fine for me, the [git repository appears to still be there](https://git.zx2c4.com/go118-netip) and proxy.golang.org should also still have it cached.

That said, the "few more weeks" from https://github.com/freifunkMUC/wg-access-server/pull/140#pullrequestreview-929566544 might be over by now, and we can consider dropping support for Go 1.17 (we _do_ already use and build the Docker images with Go 1.18) and update wgctl/wireguard-go.

**Comment by DasSkelett** [comment]
Ah okay, without proxy.golang.org in GOPROXY I receive this error:
```
go: golang.zx2c4.com/go118/netip@latest: unrecognized import path "golang.zx2c4.com/go118/netip": reading https://golang.zx2c4.com/go118/netip?go-get=1: 404 Not Found
```
Looks like it's the golang.zx2c4.com -> git.zx2c4.com link that has been removed.

**Comment by marob** [comment]
I'm having the following error:
```shell
$ go list -m -json -mod=mod all                                            
go: unrecognized import path "golang.zx2c4.com/go118/netip": reading https://golang.zx2c4.com/go118/netip?go-get=1: 404 Not Found
go: golang.zx2c4.com/go118/netip@v0.0.0-20211111135330-a4a02eeacf9d: unrecognized import path "golang.zx2c4.com/go118/netip": reading https://golang.zx2c4.com/go118/netip?go-get=1: 404 Not Found
```

I don't know go ecosystem nor how the dependency management is working.
But https://git.zx2c4.com/go118-netip URL doesn't match go118/netip ("-" instead of "/"), so I was supposing it was renamed or something (or maybe I'm misunderstanding how it works).

But, as you can see above, there is a 404.

It looks like proxy.golang.org still has some trace of it: https://proxy.golang.org/golang.zx2c4.com/go118/netip/@v/v0.0.0-20211111135330-a4a02eeacf9d.mod, but I haven't configured any proxy.

Anyway, it looks like it was a temporary module and it's going to disappear (or is already disappearing), so we have to do something.
