### ISSUE TITLE
How to write a claim mapping

### ISSUE THREAD

**Issue by thechubbypanda** [freifunkMUC/wg-access-server#207]
I'm trying to setup an admin mapping using Authentik but I'm having trouble making sense of the claimMapping. 
It sounds very powerful but I've been unable to decipher the correct keywords.

I've made a scope mapping in authentik that returns True or False depending on if the user is an admin. How do I explain that with a claimMapping?

Here's the config:

```
scopes:
      - openid
      - admin
    claimMapping:
      admin: "admin"
```

Does the claim mapping have access to the scope return value?

This is part of the well known config:

![image](https://user-images.githubusercontent.com/33595996/174677115-5ca03d37-5678-48c7-bbcc-06e78e13beb5.png)

Should the admin thing be in the claims bit instead of a scope?

**Comment by DasSkelett** [comment]
I don't know too much about OIDC apart from the basic login flow, but I think you need to publish the admin property as a user info claim, not scope, yes.

For the claimMapping expression, you receive the claims as returned as part of the user info by the server, basically as a map (similar to a JSON object). If you manage to create an `admin` claim, then your `claimMapping` should work as is.

**Comment by DasSkelett** [comment]
Hey @thechubbypanda, did the solution from https://github.com/goauthentik/authentik/issues/3135 to return a dict work?

**Comment by thechubbypanda** [comment]
Yes, returning a dict appeared to produce a working claim mapping. However I ended up looking at the groups list returned by the `profile` scope.

My claimMapping expression ended up looking like this: `"'admin' IN groups"`.
