### ISSUE TITLE
config.yaml location

### ISSUE THREAD

**Issue by hooray4me** [freifunkMUC/wg-access-server#212]
I can't seem to find where I should place my config.yaml file. I've tried putting it in the root directory of wg-access-server. It's probably staring me right in the face. Can someone point me in the right direction?

**Comment by DasSkelett** [comment]
I assume you are running it through Docker, from our images?
If so, `/config.yaml` is the location it looks at by default.
You can change it through the `WG_CONFIG` env car.

If I didn't miss anything, it looks like we haven't documented this anywhere, we should fix that.

**Comment by hooray4me** [comment]
I am using docker-compose...
![image](https://user-images.githubusercontent.com/12399138/176025144-699fb6e7-2294-44e3-bf6e-2a858cdbd6ff.png)
I've tried adding WG_Config=/config.yaml to the docker-compose and changing the ports, but it doesn't seem to want to use it.

**Comment by hooray4me** [comment]
![image](https://user-images.githubusercontent.com/12399138/176025908-a39e93e6-62ed-463c-9a08-ad7aac12d4b4.png)

![image](https://user-images.githubusercontent.com/12399138/176025930-f2045eb3-4a49-429e-91b9-06f5d8f790ca.png)

What am I missing?

**Comment by DasSkelett** [comment]
You also need to actually mount the file into the container, otherwise it can't access it. See the commented out example from the repo's docker-compose.yml (you need to uncomment it so it takes effect):
https://github.com/freifunkMUC/wg-access-server/blob/e0fbfa7fdbd58543218328288323425dfb4cd836/docker-compose.yml#L15-L17

**Comment by DasSkelett** [comment]
You need to specify the changed port inside config.yaml (or as `WG_WIREGUARD_PORT` env car). The port mapping in docker-compose.yml is only for Docker itself, the application running inside the container doesn't know about it.

**Comment by hooray4me** [comment]
ah, thanks
