### ISSUE TITLE
Add caching for the workflows

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/wg-access-server#23]
The build takes forever, a cache could shorten the build time

**Comment by DasSkelett** [comment]
https://github.com/freifunkMUC/wg-access-server/runs/4418221183?check_suite_focus=true took only 23 minutes :tada: 
And that one had to rebuild the frontend files (`npm build`), which is one of the more expensive steps, especially for cross-compiled architectures it appears.
