### ISSUE TITLE
DNS not being set in config

### ISSUE THREAD

**Issue by thechubbypanda** [freifunkMUC/wg-access-server#240]
I can't seem to get the WG_DNS_UPSTREAM to appear in the configs.  
My config is as follows:

      WG_WIREGUARD_PRIVATE_KEY: *********************************
      WG_CONFIG: /config.yml
      WG_VPN_CIDR: 192.168.1.128/25
      WG_VPN_CIDRV6: 0
      WG_IPV6_NAT_ENABLED: false
      WG_DNS_DOMAIN: vpn.example.com
      WG_DNS_ENABLED: false
      WG_DNS_UPSTREAM: "192.168.1.2"
      
I'd expect 192.168.1.2 to be set as the DNS server in the config but it's always empty :( 

I'm probably just doing something stupid but help appreciated :)

**Comment by DasSkelett** [comment]
`WG_DNS_UPSTREAM` changes the upstream of the embedded DNS proxy. The `DNS` part in the WireGuard configuration will always point to the VPN server, as otherwise you couldn't change the upstreams without breaking existing devices.

**Comment by thechubbypanda** [comment]
Ok well the actual problem I'm trying to solve is to remove the MASQUERADE from ip tables... I'm not sure if this even does it however machines on the external network can't seem to get into the vpn network. Any idea how to solve that?

**Comment by DasSkelett** [comment]
The `WG_IPV4_NAT_ENABLED` and `WG_IPV6_NAT_ENABLED` options are probably what you want, set them to `false`.
https://www.freie-netze.org/wg-access-server/2-configuration/

**Comment by thechubbypanda** [comment]
That appears to nuke my ability to connect to anything internal or external :(

**Comment by DasSkelett** [comment]
Well, you'll have to setup masquerading at the border of your network yourself with it disabled in wg-access-server, and make sure (static) routes to the VPN subnet are set up accordingly on your host and routers in your network.

Also, if you're running it in a container, you should start it with `--network=host`, as it is complex to set up proper routing into a container with changing IP addresses.

**Comment by DasSkelett** [comment]
> My network layout is as follows:
> Main [CIDR 192.168.1.0/24, Gateway 192.168.1.1, DNS 192.168.1.2]

Okay, so for this specifically, you need to make sure your gateway at 192.168.1.1 knows to route the VPN subnet 192.168.2.0/24 via the host where wg-access-server is running (192.168.1.X). And that it also correctly NATs the VPN subnet, but chances are it already does so automatically.

**Comment by thechubbypanda** [comment]
Awesome, thanks I'll try it and lyk
