### ISSUE TITLE
Base URL not configurable/respected

### ISSUE THREAD

**Issue by karypid** [freifunkMUC/wg-access-server#251]
Hello,

I tried to set up Traefik as a reverse proxy for wg-access-server using a typical set of rules that I use for other apps like portainer/smokeping/etc:

```
      - "traefik.enable=true"
      - "traefik.http.routers.wg-router.rule=PathPrefix(`/wireguard/`)"
      - "traefik.http.routers.wg-router.service=wg-access-server-wg-access-server"
      - "traefik.http.routers.wg-router.middlewares=wg-router-strip"
      - "traefik.http.middlewares.wg-router-strip.stripprefix.prefixes=/wireguard"
```

So this allows me to visit `http://host.domain/wireguard` which, which removes `/wireguard` and forwards it to the web application of wg-access-server.

> The problem is this: when I hit me docker host with the specified prefix (`http://host.domain/wireguard/`) I get redirected to the sign-in page with an HTTP 307 redirect with absolute `Location: /signin` as opposed to a relative `Location: ./signin`.

As a result my browser then hits `http://host.domain/signin` which gives a 404 error (traefik does not forward the root to wg-access-server). A relative location would have caused my browser to visit `http://host.domain/wireguard/signin` which works and displays the login screen (though actual login does not work due to the same issue).

The net result is that the web interface cannot be plugged behind a reverse proxy (at least ton under a URL prefix).

Most applications either use relative URLs everywhere, or at least allow you to configure a "base URL prefix" that is prepended to all links in responses. Is there maybe a configuration item that I am missing to set the base URL? If not, could this please be fixed on the web application? (either add a base URL configuiration, or convert all returned pages to use URLs relative to the request)?

**Comment by DasSkelett** [comment]
Yeah, currently wg-access-server only works on its own subdomain, and I would always recommend to set up different services on different subdomains. Many browser security and privacy features like CSRF and XSS protections only work based on the (sub-)domain.

I'd prefer the relative redirection approach to avoid another config knob, not sure how well this works with React though, and theoretically you can be redirected to `/signin` from any page, even `/admin/all-devices`, so the auth middleware somehow needs to deal with that as well. And the session cookie also needs to be restricted to the subpath of wg-access-server...
