### ISSUE TITLE
OIDC tokens not invalidated

### ISSUE THREAD

**Issue by SecMeyo** [freifunkMUC/wg-access-server#258]
The user's tokens do not get invalidated on signout when using an OIDC provider.

## Expected behaviour
The OIDC tokens should be invalidated via a call to the OIDC provider on logout

```
https://sso.domain.local/realms/<client-id>/protocol/openid-connect/logout?client_id=wireguard-vpn&redirect_uri=https://my.domain.local/signin?signout=1
```

## Current behaviour

Cookies get deleted but not invalidated.

## Steps to reproduce

```bash
# query for some website content
curl -i -s -k -X $'POST' \
    -H $'Host: my.domain.local' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0' -H $'Accept: application/grpc-web-text' -H $'Accept-Language: en-US,en;q=0.5' -H $'Accept-Encoding: gzip, deflate' -H $'Content-Type: application/grpc-web-text' -H $'X-User-Agent: grpc-web-javascript/0.1' -H $'X-Grpc-Web: 1' -H $'Content-Length: 8' -H $'Origin: https://my.domain.local' -H $'Dnt: 1' -H $'Referer: https://my.domain.local/' -H $'Sec-Fetch-Dest: empty' -H $'Sec-Fetch-Mode: cors' -H $'Sec-Fetch-Site: same-origin' -H $'Te: trailers' \
    -b $'auth-session=MTY2N[...]' \
    --data-binary $'AAAAAAA=' \
    $'https://my.domain.local/api/proto.Devices/ListDevices'

# signout
curl -i -s -k -X $'GET' \
    -H $'Host: my.domain.local' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0' -H $'Accept: text/html,application/xhtml+xml,application/xml;q=0.9,image/avif,image/webp,*/*;q=0.8' -H $'Accept-Language: en-US,en;q=0.5' -H $'Accept-Encoding: gzip, deflate' -H $'Dnt: 1' -H $'Upgrade-Insecure-Requests: 1' -H $'Sec-Fetch-Dest: document' -H $'Sec-Fetch-Mode: navigate' -H $'Sec-Fetch-Site: none' -H $'Sec-Fetch-User: ?1' -H $'Te: trailers' \
    -b $'auth-session=MTY2NDg[...]' \
    $'https://my.domain.local/signin?signout=1'

# query for same website content again -> response should be 307, but is 200
curl -i -s -k -X $'POST' \
    -H $'Host: my.domain.local' -H $'User-Agent: Mozilla/5.0 (Windows NT 10.0; Win64; x64; rv:98.0) Gecko/20100101 Firefox/98.0' -H $'Accept: application/grpc-web-text' -H $'Accept-Language: en-US,en;q=0.5' -H $'Accept-Encoding: gzip, deflate' -H $'Content-Type: application/grpc-web-text' -H $'X-User-Agent: grpc-web-javascript/0.1' -H $'X-Grpc-Web: 1' -H $'Content-Length: 8' -H $'Origin: https://my.domain.local' -H $'Dnt: 1' -H $'Referer: https://my.domain.local/' -H $'Sec-Fetch-Dest: empty' -H $'Sec-Fetch-Mode: cors' -H $'Sec-Fetch-Site: same-origin' -H $'Te: trailers' \
    -b $'auth-session=MTY2N[...]' \
    --data-binary $'AAAAAAA=' \
    $'https://my.domain.local/api/proto.Devices/ListDevices'
```

**Comment by DasSkelett** [comment]
Your description doesn't match the reproduction steps shown. They steps are about the wg-access-server session cookie and shoe that it keeps working, not about the OIDC token.

But the reason that the session cookie keeps working is that you don't actually sign out. The signout path is `/signout`, not `/signin?signout=1`. If you call the first one, you will be properly logged out of wg-access-server.

---

For the separate OIDC token topic: yes, after logging out of wgas you may still stay logged in at the OIDC provider.
The effectiveness of the logout functionality depends on the behaviour of the provider, e.g. whether it keeps users logged in or requires a new authentication after browser restart and so on.
Unfortunately the OIDC spec doesn't include a solution for this issue, i.e. a way to tell the provider to log you out for this application only, see also the discussion in https://github.com/freifunkMUC/wg-access-server/issues/213#issuecomment-1172558699
There is single sign-out, but I believe it would be unwanted in many situations.

I assume the `https://sso.domain.local/realms/<client-id>/protocol/openid-connect/logout` URL is a custom addition of your Auth provider? Do you know some documentation on this?

**Comment by SecMeyo** [comment]
>Your description doesn't match the reproduction steps shown. They steps are about the wg-access-server session cookie and show that it keeps working, not about the OIDC token.

Oh I see. That's an even easier fix then I guess. 

>But the reason that the session cookie keeps working is that you don't actually sign out. The signout path is /signout, not /signin?signout=1. If you call the first one, you will be properly logged out of wg-access-server.

nope, same result if step 2 is changed to /signout. The cookie does not get invalidated, just deleted on the client side. When I klick on "Logout" and then visit the main page, I am logged in again (even without manipulating the cookies).

I am using Keycloak. Was not aware that the logout function was not part of OIDC, here are the docs:  
https://www.keycloak.org/docs/latest/securing_apps/#logout

**Comment by GoliathLabs** [comment]
@SecMeyo for me the lougout/signout works perfectly with keycloak. After clicking Logout i'm being redirected to `https://my.domain.local/signin?signout=1` . Using Keycloak as well. What does your config look like? (omitting sensitive vaules)
![image](https://user-images.githubusercontent.com/8057646/197528367-ef9a10b8-1bc3-41f0-9158-5879dd666277.png)
