### ISSUE TITLE
A configuration with same name can override an existing one 

### ISSUE THREAD

**Issue by nathanael-h** [freifunkMUC/wg-access-server#260]
A configuration with same name can override an existing one 
Steps to reproduce: 

1. Go to web interface
2. Login as user (in my case via OIDC)
3. Add a config with name "abc", download the config file and look for the keys
4. Again, add a config with the name name "abc", download the config file and look for the keys, which are different. 
5. Check in databse, only the second configuration exists. The previous was overwritten. 

I could look for a PR preventing user to reuse the same name. 
Version 0.8.0.

**Comment by GoliathLabs** [comment]
You're right. Would you be willing to provide a PR for this issue?

**Comment by nathanael-h** [comment]
Yes, I did not start work on this, but with a few tips I'd be ok to send a PR. Could you guide me a little bit?

**Comment by GoliathLabs** [comment]
I think you should have a look at the `AddDevice` function (https://github.com/freifunkMUC/wg-access-server/blob/master/internal/devices/devices.go#L64) and check whether the device name is already in the database (https://github.com/freifunkMUC/wg-access-server/blob/master/internal/devices/devices.go#L130). The check should return something like "device name already taken" if it already exists.

**Comment by GoliathLabs** [comment]
@nathanael-h what is the current status? Have you already had time to work on it? We would like to make a release soon and wanted to know if this patch will be included or not

**Comment by nathanael-h** [comment]
Hi, I did not start, no time for now. What is the ETA for your release? Maybe I could try to make it on time. But I don't wand to delay it.
