### ISSUE TITLE
High Availability

### ISSUE THREAD

**Issue by TafkaMax** [freifunkMUC/wg-access-server#371]
Hi

I would like to understand, what kind of HA do you support experimentally?

https://www.freie-netze.org/wg-access-server/3-storage/

Looking at this, do you support HA postgres instances using pg-bouncer? Or do you support two instances of wg-access-server against one backend?

Thanks!

**Comment by GoliathLabs** [comment]
If I remember correctly, that would be multiple instances of wg-access-server. This feature is from the former upstream and I haven't tested it yet. Maybe @DasSkelett can say something about it?

**Comment by gedw99** [comment]
Also curious about this area

**Comment by nathanael-h** [comment]
I use a deployment of multiple wg-access-server, all using the same postgresql server as database. Thus, all servere have the same configurations loaded in (or deleted). This allows me to have HA on wg-access-server level. (HA for postgresql is out of scope I think, as it is a big topic).

**Comment by GoliathLabs** [comment]
As @nathanael-h pointed out, you could spin up multiple instances of wg-access-server with the same pg backend. PG can also be made HA using something like repmgr (http://www.repmgr.org/; https://hub.docker.com/r/bitnami/postgresql-repmgr/). We don't currently use HA in our deployments, but these solutions should work for you.

**Comment by gedw99** [comment]
You can get HA db on fly.io. 

They replicate the db for you
