### ISSUE TITLE
Missing docs for disable-inactive WG_DISABLE_INACTIVE, misleading name, incorrect default value

### ISSUE THREAD

**Issue by spirkaa** [freifunkMUC/wg-access-server#396]
I understand that this is not stable release and things may change at any time, but still.

Introducing destructive changes https://github.com/freifunkMUC/wg-access-server/pull/305 as enabled by default it is not a good idea. And there is no updated docs describing this new (niche) feature.

After recreating docker container some of my connections was incorrectly detected as Last Seen 2022 years ago, and then successfully removed from server.

**Comment by nwaldispuehl** [comment]
Agreed, this is not a sensible default.
- The feature should be disabled by default. 
- The deactivation semantics should be reversed, i.e. the setting should be renamed to 'enable..'.
