### ISSUE TITLE
Interface not cleaned up in case of fatal error

### ISSUE THREAD

**Issue by nwaldispuehl** [freifunkMUC/wg-access-server#418]
There is one little bug I would like to fix before the release of the `0.10.0` version, and I could use a helping hand of one of you go pros:
@GoliathLabs  @DasSkelett @fbuetler

The symptom is that if the wg-access-server stops due to a fatal error, e.g. when my Keycloak container is not yet started and it hits this line in [`oidc.go#45`](https://github.com/freifunkMUC/wg-access-server/blob/master/pkg/authnz/authconfig/oidc.go#L45):

```
logrus.Fatal(errors.Wrap(err, "failed to create oidc provider"))
```
then this `Fatal` function ultimately calls `os.Exit(1)` which causes this statement in [`main.go#125`](https://github.com/freifunkMUC/wg-access-server/blob/master/cmd/serve/main.go#L125) to be ignored:
```
defer wgimpl.Close()
```
This means that the interface is not cleaned up and upon the new start of the wg-access-server , the configured interface is already present and the server fails again.

---

How could the situation be improved?

Some ideas:

- One possibility would probably be to change the `Fatal` statements to `Panic`, but this has slightly different semantics.
- Then we could register yet another logrus hook, which fires only for 'fatal' entries and would close the interface, but I have no idea how to access the interface in `cmd/serve/main.go` from the hook in `/main.go`. Plus this is some side-effect which has kinda bad taste to it.
- I guess there are no termination hooks?

Does anyone know how to do it the go way^TM?

**Comment by fbuetler** [comment]
I also ran into this issue lately 😅 

I'd actually say `panic` and `recover` is the way to go here.

With `panic(errors.Wrap(err, "failed to create oidc provider"))` in [oidc.go#45](https://github.com/freifunkMUC/wg-access-server/blob/master/pkg/authnz/authconfig/oidc.go#L45) deferred functions are executed and a proper cleanup is possible.

Additionally, we can defer a `recover()` function to "catch" the panic and exit cleanly without leaking the stack trace to the user.

```go
defer func() {
	if err := recover(); err != nil {
		logrus.Fatal(err)
	}
}()
```
in [main.go#80](https://github.com/freifunkMUC/wg-access-server/blob/master/cmd/serve/main.go#L80).

Sidenote: I noticed that there are already quite some panic in `oidc.go`.

**Comment by nwaldispuehl** [comment]
> I'd actually say `panic` and `recover` is the way to go here.

Thanks for the directions! :smiling_face_with_three_hearts:
