### ISSUE TITLE
Release v0.9.1

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/wg-access-server#425]
@nwaldispuehl I was testing the current master for a longer time now, and I think it's ready for release.

What do you think? The new features y'all worked on are pretty amazing :).

**Comment by nwaldispuehl** [comment]
Thanks a lot! :blush: 

`0.9.1` was also my choice of a next version initially, but:
- the new additions consist not only of bugfixes, but of new features as well, and
- the [wg-embed](https://github.com/freifunkMUC/wg-embed) project already published a [`0.9.1`](https://github.com/freifunkMUC/wg-embed/releases/tag/v0.9.1)-version some weeks ago, and I'd love to squeeze the  new server MTU feature [#417](https://github.com/freifunkMUC/wg-access-server/issues/417) ([pending PR in `wg-embed`](https://github.com/freifunkMUC/wg-embed/pull/19)) of @fbuetler into the next release as well, _and_ have the versions of the two projects synced,

which caused me to propose a jump to the next minor release `0.10.0` for which I created a milestone and already assigned all issues: https://github.com/freifunkMUC/wg-access-server/milestone/2

Would it be ok for you if we can do it in the next few weeks? Or would you rather skip on this last feature?

**Comment by awlx** [comment]
You are totally right `0.10.0` seems like the way to go :). I somehow forgot the check the milestones 😨. 

I just didn't want the users missing out on all the cool new features your team implemented <3. But yes, let's do it as you initially planned!
