### ISSUE TITLE
Release v0.10.0

### ISSUE THREAD

**Issue by nwaldispuehl** [freifunkMUC/wg-access-server#430]
@awlx meanwhile the last open issue for the `v0.10.0` has been merged, so from our side everything would be ready for the release.

**Comment by nwaldispuehl** [comment]
For this release changelog I'd propose an additional section at the top with some kind of a discussion of some features for easier adaptation of new configuration items, along the lines of:

---

### Notable configuration changes

With #401 and #429 the maximum transmission unit ('MTU') of the server and client interfaces can now each be configured with a new configuration item:

#### Server MTU
YAML configuration file / Helm chart:
```
wireguard:
  ...
  mtu: 1420
```
Environment variable: `WG_WIREGUARD_MTU`
CLI argument: `--wireguard-mtu`

If omitted, a default MTU of `1420` is used (as before).

#### Client MTU
YAML configuration file / Helm chart:
```
...
clientConfig:
  ...
  mtu: 1380
...
```
Environment variable: `WG_CLIENTCONFIG_MTU`
CLI argument: `--clientconfig-mtu`

If omitted, the client uses a default at its own discretion, usually `1420` as well.

**Comment by nwaldispuehl** [comment]
@awlx Should I do the release, or are you still testing?
@GoliathLabs Are there pending dependency PRs for this release?

**Comment by awlx** [comment]
For me everything looks fine master is running without issues since 6 days on our prod vpn :).
