### ISSUE TITLE
Migrate from Create React App to alternative

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/wg-access-server#579]
There are a number of good alternatives we should explore, as CRA hasn't seen an update in a while and is now considered deprecated. 
A proper discussion can be found here: https://github.com/reactjs/react.dev/pull/5487

Maybe vite would be a reasonable replacement for react scripts?

**Comment by nwaldispuehl** [comment]
Has this been solved with the #584 PR?

**Comment by GoliathLabs** [comment]
Yes, you're right
