### ISSUE TITLE
Import existing config, show QR Code again

### ISSUE THREAD

**Issue by Bouni** [freifunkMUC/wg-access-server#58]
Hi,

I wnt to switch from [vx3r/wg-gen-web](https://github.com/vx3r/wg-gen-web) to [freifunkMUC/wg-access-server](https://github.com/freifunkMUC/wg-access-server).

I have existing configurations and ideally I would like to import them. Is there a way to do that?

And my second question is, is there a way to show the QR code again or download the config file at a later point in time?

**Comment by DasSkelett** [comment]
Hey,
there's no built-in way to import existing configurations from other projects. If you really need to, you could manually insert the data into the database (SQLite, PosgreSQL, MySQL), but it's probably not worth it.

Client QR codes and configs cannot can't be re-displayed. That would require the private key, which the server doesn't store. But you can just delete the old device and create a new one.

**Comment by Bouni** [comment]
Ok, thanks for you answers!
