### ISSUE TITLE
Point-To-Point vpn configuration help

### ISSUE THREAD

**Issue by phyzical** [freifunkMUC/wg-access-server#582]
Hey there,

Thanks for continuing to maintain this is easy to get going and use. 

Im just wondering if there is any way to edit the generic `wg0.conf` that the server would use? looking in the source it looks to be abstracted away is that correct?

i was hoping to try something like this https://www.digitalocean.com/community/tutorials/how-to-create-a-point-to-point-vpn-with-wireguard-on-ubuntu-16-04

hoping that we can have 1 vpn configuration for clients to connect to as the "base/core" that then talks to other servers in other subnets/locations.

Or does adding another client via the ui do this anyway? the only issue i see is i need to be able to set the endpoint also which the ui doesn't support?

```
[Peer]
PublicKey = public_key_of_first_server
AllowedIPs = 10.0.0.1/32
Endpoint = public_IP_of_first_server:5555
```

**Comment by phyzical** [comment]
Ah yes, if i run wg show ont he running container i do infact see the peer chunks.

So i guess this actually becomes a feature request to support an optional endpoint field.

I think i can just use the wg commands to manually edit in the interim though, if i get it all working ill have a look at how hard the implementation would be pr wise 👍

**Comment by phyzical** [comment]
i do agree with the thinking, given what the project is aims todo. 

At the same time functionality wise to achieve this, its just a matter of supporting the `endpoint` and `persistantkeepalive` (i think) i am currently running it on two eks clusters

 but will post back if i am wrong with this thinking and it doesn't end up working at all 😆

**Comment by phyzical** [comment]
i think i need to keep doing some more reading, while the changes i made did allow me to connect two pods, i wasnt able to ping either way 

Incase someone else knows a better way to go about this what i am after is;

 *  I have 3 peers A,B,C.
 * A and C are connected to B.
 * connected as A i can resolve dns of the network B is running in
 * connected as A i cant seem to get it to be able to resolve anything in C's network.

**Comment by GoliathLabs** [comment]
If someone wants to take this on, feel free. As @DasSkelett already mentioned, s2s functionality is not the intended purpose of this project. However, if anyone is willing to put in the effort, we are open to a PR for this feature.
