### ISSUE TITLE
Support passing secrets for oidc and session via ENV or CLI

### ISSUE THREAD

**Issue by andi0b** [freifunkMUC/wg-access-server#587]
Right now some secrets can only be set via the config file, for example:
- `auth.sessionStore.secret`
- `auth.oidc.clientSecret`
- `auth.gitlab.clientSecret`

It would be great if those could be passed via an environment variable or optionally mounted as secret file.

Right now I need to treat the whole config.yaml as a secret itself, which is a bit cumbersome.

Edit: I just noticed that the official helm chart already has a solution for injecting secrets into the config.yaml, which seems to work but is just not documented: https://github.com/freifunkMUC/wg-access-server-chart/blob/4061059fff247c632c3e557963f5b0d39d6903ee/charts/wg-access-server/templates/deployment.yaml#L32

**Comment by GoliathLabs** [comment]
@andi0b Would you be open to adding that to the documentation?
