### ISSUE TITLE
Manifest: Line: 1, column: 1, Syntax error.

### ISSUE THREAD

**Issue by T0biii** [freifunkMUC/wg-access-server#619]
Some how the manifest.json are broken?
![image](https://github.com/freifunkMUC/wg-access-server/assets/5702338/ffe15f59-033d-48b5-bd8f-83d6de88ab0e)

**Comment by nwaldispuehl** [comment]
The file looks fine to me (although oddly indented).
Where do you find this syntax error?

**Comment by T0biii** [comment]
after Login in at: https://vpn.ffmuc.net/

![image](https://github.com/freifunkMUC/wg-access-server/assets/5702338/2a69e19c-a346-41de-b220-0bae559162e2)

![image](https://github.com/freifunkMUC/wg-access-server/assets/5702338/83500f5c-c4ee-404c-828e-25670c3fdaee)
looks like the code for the SignIn Page

**Comment by nwaldispuehl** [comment]
Hmm, ok. Locally this does not occur for me, but I will upgrade our company instance to the latest version this week to check it.
What browser are you using?

By the way; did you notice that this web application manifest specification is only a draft?
https://w3c.github.io/manifest/

**Comment by T0biii** [comment]
Some Features are experimental but it is supportet since Chrome Version 39: 
https://developer.mozilla.org/en-US/docs/Web/Manifest#browser_compatibility
and the pr was there for discussion but got merged fast:
https://github.com/freifunkMUC/wg-access-server/pull/613

**Comment by nwaldispuehl** [comment]
I was able to reproduce it with our company instance. There might be something off with the routing.
We would need to reproduce it with the dev server, preferably. I might idly look into it if I find the time.
Feel free to also investigate.

**Comment by T0biii** [comment]
if you build the website with 
`cd website && npm install && npm run build`
and then run the go server:
`sudo go run ./main.go serve`
can get the Server

But without the build I could not reproduce the problem at the moment.

**Comment by nwaldispuehl** [comment]
Ah, I also get the error after having done the `npm run build`, something I never did before. :+1: 
(Got to add it to the dev documentation.)

**Comment by GoliathLabs** [comment]
![image](https://github.com/freifunkMUC/wg-access-server/assets/8057646/95c250f3-1c89-4528-a697-6e004502542a)
can't be reproduced on my side with the latest release.
