### ISSUE TITLE
Use proper tags for releases

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/wg-access-server#68]
To make this project more stable, we should use proper Github releases and tags.

**Comment by GoliathLabs** [comment]
That's what I've thought about too as I'm normally using tagged versions anyways

**Comment by GoliathLabs** [comment]
We still need to implement building and pushing tags to the ghcr
While we're on it we might also add dockerhub as a second container registry?

**Comment by awlx** [comment]
@GoliathLabs PRs are welcome :). I don't know if we really need a second registry.
