### ISSUE TITLE
Add Docker Hub as a second registry

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/wg-access-server#71]
We should also push our images to Docker Hub as this is the far more popular registry and new users can see that we are also pushing newer images that can replace the upstream images on Docker Hub

**Comment by DasSkelett** [comment]
What made me finally abandon Docker Hub was their (then newly added) restriction of only _one_ personal access tokens for free accounts. I definitely do not want to share a single token across all my devices, GitHub repos, GitLab repos etc.
That might not be a issue for FFMUC if we just set an organization-wide secret. Or maybe a paid subscription to fully get rid of this restriction (and any others that we might hit).

**Comment by GoliathLabs** [comment]
Yeah, their pricing is quite ridiculous
![image](https://user-images.githubusercontent.com/8057646/150865020-ab71abb6-1a67-4e16-ace3-96b5e1fd1d10.png)

**Comment by GoliathLabs** [comment]
Nonetheless I've contacted @awlx if we could add my token in the meantime as we're using ghcr.io anyways

**Comment by awlx** [comment]
Tbh, sticking it to an account makes me ... not wanting to publish it on Dockerhub @GoliathLabs.
