### ISSUE TITLE
error on arm devices

### ISSUE THREAD

**Issue by stephensworld** [freifunkMUC/wg-access-server#739]
Hi,

I got this error on arm devices like raspberry or arm64 vm.

ERRO[0000]main.go:152 failed to load WireGuard config: failed to set interface ip address: failed to set ip address of wireguard interface: permission denied 

Best regards
Stephan

**Comment by awlx** [comment]
Looks like you are missing some permissions to manipulate the interface. Did you check if you have CAP_NET_ADMIN set if this runs in docker?

**Comment by stephensworld** [comment]
Hi, I tried this:
docker run \
  -it \
  --rm \
  --cap-add NET_ADMIN \
  --device /dev/net/tun:/dev/net/tun \
  --sysctl net.ipv6.conf.all.disable_ipv6=1 \
  --sysctl net.ipv6.conf.all.forwarding=1 \
 -v wg-access-server-data:/data \
  -v /lib/modules:/lib/modules \
  -e "WG_ADMIN_PASSWORD=xxxxxxxxxx" \
 -e "WG_EXTERNAL_HOST=xxxxxxxx" \
  -e "WG_WIREGUARD_PRIVATE_KEY=xxxxxxxxxxxx" \
  -e "WG_VPN_ALLOWED_IPS=0.0.0.0/0" \
  -e "WG_DNS_UPSTREAM=192.168.6.5" \
  -e "WG_WIREGUARD_PORT=54280" \
  -p 8000:8000/tcp \
  -p 54280:54280/udp \
  ghcr.io/freifunkmuc/wg-access-server:latest

But I get this error
