### ISSUE TITLE
Add a proper PR / Issue template to this repo

### ISSUE THREAD

**Issue by GoliathLabs** [freifunkMUC/wg-access-server#74]
Hello,
we may want to add a proper template for issues and PR requests to this repo, so that we can get useful information in case of issues or a proper description for new features and pull requests.

**Comment by T0biii** [comment]
maybe we should then use a template for all our Repos?
In this Repo: https://github.com/freifunkMUC/.github you can place PR / Issue template.

**Comment by GoliathLabs** [comment]
@T0biii That's a good idea. Is it possible that the templates are overwritten in certain repositories, since it's hard to find templates that fit them all?

**Comment by T0biii** [comment]
> @T0biii That's a good idea. Is it possible that the templates are overwritten in certain repositories, since it's hard to find templates that fit them all?

yea i think so, you can overwrite it, just create a template in the repo where you dont want it
