### ISSUE TITLE
Help wanted for maintaining Helm Charts

### ISSUE THREAD

**Issue by awlx** [freifunkMUC/wg-access-server#97]
Hello Kubernetes and Helm users!
We need help maintaining the Helm Chart, its documentation and other k8s-related things that might come up.
Nobody of the "freifunkMUC team" has the necessary knowledge for this, and none of us deploy it using Helm.

We've already set up a new repository, because I believe it will be easier to separate it from this one.
https://github.com/freifunkMUC/wg-access-server-chart

If you use the Helm Chart, get in touch to take over maintenance, as **otherwise it will be gone completely with the next release**.

---

**Original issue:**

With branch protection enabled, the Helm update workflow cannot push to master as it's a protected branch.

```
create mode 100644 docs/charts/wg-access-server-v0.5.2.tgz
remote: error: GH006: Protected branch update failed for refs/heads/master.        
remote: error: 6 of 6 required status checks are expected. At least 1 approving review is required by reviewers with write access.        
To https://github.com/freifunkMUC/wg-access-server
 ! [remote rejected] master -> master (protected branch hook declined)
error: failed to push some refs to 'https://github.com/freifunkMUC/wg-access-server'
```

We can either workaround this by letting it open a new PR instead of pushing straight to the repo. Or setting a GITHUB secret with an API Token of an admin, to elevate the permissions.

**Comment by elcomtik** [comment]
I can see that issue still persist as I looked that action for 0.6.0 failed wit same error as @awlx reported. I can see that once before it run successfully, how's that possible?

**Comment by DasSkelett** [comment]
For the last run @awlx removed the branch protection briefly and re-ran the workflow.
The workflow permissions should've been updated in the meantime, but it looks like that wasn't successful.

**Comment by elcomtik** [comment]
@DasSkelett CWoul you please remove branch protection and re-run helm update action to publish 0.6.0 chart?

**Comment by DasSkelett** [comment]
I can't, I don't have the necessary admin rights in this repo. We'll have to wait for @awlx to have time to do it.

**Comment by awlx** [comment]
@DasSkelett it's fixed already I disabled the protections

**Comment by DasSkelett** [comment]
@DerRockWolf @elcomtik @zandemax would one of you like to take over maintenance of the Helm and Kubernetes files and packages in a separate repository?

I don't think our poking and tinkering is very fruitful. Nobody of us uses Helm and has much experience with it. I believe you would get a more pleasant experience doing it yourselves, being much more familiar with the topic. And it might be easier working on it in your own separate repo.
We can of course link to your repository to direct other Helm users towards you.

**Comment by elcomtik** [comment]
I can take maintenance of chart. The question is if you want it under your GitHub organization or not. 

I'm also considering creating ansible role for deployment without k8s.

**Comment by awlx** [comment]
We can create a repo under this org if you like, but also feel free to do it under a different org :).

**Comment by elcomtik** [comment]
I think that, it would be accepted better by community, if the app and chart repo stays under one org

**Comment by zandemax** [comment]
I'm also happy to assist in the maintenance of the Charts if needed, @elcomtik

**Comment by elcomtik** [comment]
Any help is welcomed. 

Initially I would like to create repo and gh page pointing to eg. charts.freie-netze.org and put there our existing chart.

I would like to create build it like Authelia does. You can look at https://charts.authelia.com/ and their charts repository https://github.com/authelia/chartrepo

Charts are versioned independently on app releases, so chart features can be added continuously.

**Comment by awlx** [comment]
Any wishes for the naming? I will create the repo right away and make you maintainers :).

**Comment by elcomtik** [comment]
Let it be charts, or if you want it to be dedicated to wg-access-server only, then wg-access-server-chart.

**Comment by elcomtik** [comment]
Additionally I would propose to abandon k8s manifest maintenance. I looked on it and currently it seems to be generated from helmchart and in my opinion it provides no additional value.

**Comment by zandemax** [comment]
> Additionally I would propose to abandon k8s manifest maintenance. I looked on it and currently it seems to be generated from helmchart and in my opinion it provides no additional value.

I'd concur with that, there is no real use in having dedicated k8s manifests outside the helm chart. If one really needs them they can get them out of the helm charts by rendering it locally. (Maybe we could consider a hint to the helm `template` command in the docs for anyone looking for that)

**Comment by awlx** [comment]
@zandemax @elcomtik I invited you both to the team and created the repo.

**Comment by elcomtik** [comment]
Thanks, I already joined. I will move with this conversation into chart repo issues.

**Comment by DerRockWolf** [comment]
I would also be happy to assist you two 😄

@elcomtik 
> I would like to create build it like Authelia does.

That looks great! I think it would be valuable if we would maintain a `CHANGELOG.md` and/or put the changes into the release like the [cortex chart](https://github.com/cortexproject/cortex-helm-chart) does it.

**Comment by elcomtik** [comment]
@DerRockWolf you are welcomed to join us. 

> That looks great! I think it would be valuable if we would maintain a CHANGELOG.md and/or put the changes into the release like the [cortex chart](https://github.com/cortexproject/cortex-helm-chart) does it.

Of course we can add it.

**Comment by DasSkelett** [comment]
Is there a way we can assist you three (that doesn't require k8s/Helm knowledge)?
I'd like to remove all Helm files and the workflow from this repository before the next release.

**Comment by GoliathLabs** [comment]
@elcomtik @DerRockWolf @zandemax any updates on this? There hasn't been much activity in the chart repo lately.

We want to "migrate" the helm files & the corresponding workflow over to the new chart repo before publishing the new release. Otherwise the files will be removed from wg-access-server for the time being.

**Comment by elcomtik** [comment]
I'm sorry for inactivity, I've been busy past weeks. Panning to work on this soon. 

Do you have set a date for removal from original repo?

**Comment by DasSkelett** [comment]
As soon as possible ;) I am considering a small release with a few bugfixes this week/weekend, and I want the files to be gone by then so we don't run into any issues with the workflow again.

**Comment by GoliathLabs** [comment]
What about you @DerRockWolf & @zandemax are you still interested?

**Comment by DerRockWolf** [comment]
I am still interested but I sadly have little time to support at the moment.

**Comment by DasSkelett** [comment]
Removal in progress: https://github.com/freifunkMUC/wg-access-server/pull/164
Keeping the existing chart packages for now, but will remove soon as well so people don't stay behind on outdated versions.

**Comment by iMartyn** [comment]
I could join the effort.  For now I've restored the folder on a fork, and fixed up the chart to work.  I would actually say that breaking it into a separate repo is a bit overkill, I'm not sure that the release asset trick will work for anyone expecting a real repo though, e.g. argocd, flux etc. users. (I'm an argocd user).

**Comment by GoliathLabs** [comment]
The problem is that it requires quite a bit of maintenance to keep the charts up to date, and neither @DasSkelett nor I have a kubernetes/helm deployment running. As you can see, the interest in maintaining these charts has been pretty low for quite some time. What would you suggest instead?

**Comment by iMartyn** [comment]
I don't feel like it should be a lot of maintenance.  The main annoyances can be CI'd away.  For instance in my last few places for internal charts we ended up using sed in the pipeline, so basically `appVersion` and in a public chart like this one `version` would be placeholders, then before `helm package` runs, you pull the version from whatever CI is building, which saves automated commits (which I generally dislike) for that.  Then it's just publishing, which if you're not using github pages for anything else, why not use that and take the easy path of the github action that does the publish?  I'm happy to step up and help fixup the helm chart for issues people have with the existing helm chart.

**Comment by DasSkelett** [comment]
Hey @iMartyn, thanks for wanting to help. Have a look at https://github.com/freifunkMUC/wg-access-server-chart, @NismoFur and @Strangerxxx started to work on it over there. Please coordinate with them, and feel free to open pull requests there.

> would actually say that breaking it into a separate repo is a bit overkill

I would prefer it this way, the packaging should be separate and especially all these compressed binary blobs shouldn't end up in this repository, they inflate the repository size too much.
Also it appeared to be easier as all the automation we tried to setup here already didn't work.

> I don't feel like it should be a lot of maintenance.

That would be ideal, the less work y'all have the better ^^ (For me it would be a lot of effort as I don't know anything about Helm or Kubernetes)

>  Then it's just publishing, which if you're not using github pages for anything else, why not use that and take the easy path of the github action that does the publish?

We are already using GH Pages for our documentation: https://freie-netze.org/wg-access-server
That said, we still used it for publishing the helm chart packages as well, which worked per se, except we couldn't get the CI to work 100%. There's more information in all the previous Helm issues and pull requests.
But I think it might easier in a separate repo, with GitHub pages set up just for the chart files.

> I'm happy to step up and help fixup the helm chart for issues people have with the existing helm chart.

Thanks so much!

**Comment by catrielmuller** [comment]
I created a PR to do the Deployment and fix the documentation.
in a meantime you can use my repo if you needed.

```bash
$ helm install wireguard --repo https://catrielmuller.github.io/wg-access-server-chart/ wg-access-server
```

**Comment by GoliathLabs** [comment]
More or less done by the colleagues at @inventage among others
